### PR TITLE
Add cross version support for Scala 2.12

### PR DESCRIPTION
**Pull request by reynoldsm88**
Scala 2.11 is still supported, you can build and test with both versions using `sbt +compile` and `sbt +test`

### CODE REVIEW

**Comment by reynoldsm88** [comment]
@barneygovan i'm not sure how active you are in maintaining this repository, but i like this library and would like to continue using it. it would be really nice if updated versions could be pushed to nexus.

would you mind merging this PR and doing a release, otherwise, can you give me control of this repository so that I can merge and do a sonatype release?

**Comment by barneygovan** [comment]
Hi @reynoldsm88 -- I'm not very active, unfortunately, mostly due to work and not working with Scala any more.  

I'll assign you the repo, and thanks for taking this over -- my little project will live :)

**Comment by reynoldsm88** [comment]
@barneygovan hey thanks for replying, i totally understand. i changed the name of my fork, so I think things should be okay.

**Comment by barneygovan** [comment]
It's still saying I cannot transfer, and it sounds like it's because your fork is still in the network of this repo.

What I suggest is:
* I'll review this PR and merge it with the main branch
* You will have to delete your fork (or contact github support to have them detach it)
* I'll transfer ownership to you

**Review by barneygovan — APPROVED** [review]
LGTM

**Pull request merged**
